# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64)),
                ('letter', models.CharField(max_length=1)),
                ('person', models.CharField(max_length=64)),
                ('channel', models.CharField(max_length=16)),
                ('state', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=1024)),
                ('answer', models.NullBooleanField(default=None)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botticelli.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Stump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=1024)),
                ('answer', models.NullBooleanField(default=None)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botticelli.Game')),
            ],
        ),
    ]
