# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botticelli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='thread_ts',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='stump',
            name='thread_ts',
            field=models.CharField(default='', max_length=32),
        ),
    ]
